# Generated by Django 3.1.5 on 2021-02-11 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0002_auto_20210204_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionconsumed',
            name='prod_report',
        ),
        migrations.AddField(
            model_name='productionconsumed',
            name='produced',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.productionproduced'),
            preserve_default=False,
        ),
    ]
